alert("Hello there, welcome to my website");
let name = ("Rachel");
console.log(name);
let age =(23);
console.log(age);
let num1 =(20);
console.log(num1);
let num2 =(3);
console.log(num2);
let sum =(num1+num2);
console.log(sum);
let num3 =(9);
console.log(num3);
let num4 =(50);
console.log(num4);
let difference =(num3-num4);
console.log(difference);
let num5 =(10);
console.log(num5);
let num6 =(30);
console.log(num6);
let quotient =(num6/num5);
console.log(quotient);
let num7 =(12);
console.log(num7);
let num8 =(3);
console.log(num8);
let product =(num8*num7);
console.log(product);
let num9 =(15);
console.log(num9);
let num10 =(4);
console.log(num10);
let remainder =(num9%num10);
console.log(remainder);
let x =(40);
console.log(x);
let y =(22);
console.log(y);
let boolen =(x > y);
console.log(boolen);
let apples =(7);
console.log(typeof(apples));
let friend =("Rencia");
console.log(typeof(friend));
